# Generated by Django 5.1.3 on 2024-11-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': [('can_verify_feedback', 'Can verify feedback'), ('can_view_all_feedback', 'Can view all feedback'), ('can_delete_feedback', 'Can delete feedback'), ('can_add_feedback', 'Can add feedback'), ('can_update_feedback', 'Can update feedback')]},
        ),
    ]
